version: '3.9'
services:
    db:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${COMPANY_NAME}
            TZ: America/Sao_Paulo
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    mysql:
